services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /data/coolify/applications/m13aql8ty4pu98f7oujxj5cz/uploads-photos:/var/www/html/public/uploads/photos

  fp-sync-agent:
    build:
      context: ./fp-sync-agent
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEVICE_IP=${FP_DEVICE_IP}
      - DEVICE_PORT=4370
      - PHP_APP_CALLBACK_URL=
      - PHP_APP_API_KEY=${FP_SYNC_API_KEY}
      - PULL_LOG_INTERVAL_MINUTES=15